### ISSUE TITLE
Upload data loading!

### ISSUE THREAD

**Issue by wessammickey** [patriciamar/ShinyItemAnalysis#457]
Greetings,

I have been trying to upload my small data of 15 items so I can conduct item analysis. It is always loading and nothing is happening. Please, let me know what I need to do to use my own data and conducting ShinyitemAnalysis.

**Comment by patriciamar** [comment]
Hello,
which version of ShinyItemAnalysis are you using? Please try the newest GitHub version 1.3.5-1. Some issues with data loading appeared in version 1.3.5 and are now solved with the 1.3.5.-1 version.

**Comment by wessammickey** [comment]
Thank you for your prompt response! I downloaded the newer version successfully. However, it is still loading. It didn't fix it for me. I am wondering if it has to do anything with IP address, since I am in the US. I would appreciate your help with this fascinating tool that you created. Thanks!

**Comment by patriciamar** [comment]
Your location should not be an issue. You may try the tool online at https://shiny.cs.cas.cz/ShinyItemAnalysis/ or at https://cemp.shinyapps.io/ShinyItemAnalysis. However, my suspicion is that there is something wrong in your data format. Please refer to the R journal article:
Martinkova, P., & Drabinova, A. (2018). ShinyItemAnalysis for teaching psychometrics and to enforce routine analysis of educational tests. The R Journal, 10(2), 503-515, https://doi.org/10.32614/RJ-2018-074. 
In the Supplementary material, you may find sample data and check the format.
Thanks for your positive feedback, we are always glad when the software is being used and cited as helpful.

**Comment by wessammickey** [comment]
It is working now. Thank you for your contribution to the field! This is fascinating. 
I was wondering if distractor analysis can be done through the package too.

**Comment by patriciamar** [comment]
Thanks for letting me know, I am glad it is working now! Some distractor analysis is available with function DistractorAnalysis() and plotDistractorAnalysis(). In future, we are thinking about providing functionalities of ItemAnalysis() function also for distractors.
